export const START_LOADING_COURSES = 'START_LOADING_COURSES'
export const SUCCESSFULLY_LOADED_COURSES = 'SUCCESSFULLY_LOADED_COURSES'

export const ADD_COURSE = 'ADD_COURSE'
export const FAILED_LOADING_COURSES = 'FAILED_LOADING_COURSES'