export const START_LOADING_COURSES = "START_LOADING_COURSES";
export const SUCCESSFULLY_LOADED_COURSES = "SUCCESSFULLY_LOADED_COURSES";

export const START_LOADING_COURSE = "START_LOADING_COURSE";
export const SUCCESSFULLY_LOADED_COURSE_ROUNDS = "SUCCESSFULLY_LOADED_COURSE_ROUNDS";

export const ADD_COURSE = "ADD_COURSE";
export const FAILED_LOADING_COURSES = "FAILED_LOADING_COURSES";

export const SUCCESSFULLY_CREATED_ROUND = "SUCCESSFULLY_CREATED_ROUND";